### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by sandraole** [Ethervortex/opeapu#1]
- Dokumentaatio on ajan tasalla.
- README.md on todella selkeä ja sovelluksen testaukseen tarvittavat ohjeet ovat riittävät.
- Pidän siitä miten README tiedostoon on kirjattu ylös sovelluksen toimintoihin liittyvät ominaisuudet kuten esim. navigointipalkki tai  mitä kaikkea kultakin sivulta löytyy. Se antaa hyvän mielikuvan tulevasta sovelluksesta.
- En valitettavasti pystynyt testaamaan sovellusta omien lokaalien ongelmien vuoksi.
- Sovelluksen koodi ja rakenne ovat todella hyvät. Olet myös saanut hyvin edistettyä sovellusta.
- Sovelluksen aihe on hyödyllinen ja käytännöllinen! Kyseisessä sovelluksessa on lähdetty parantamaan jo toimivaa konseptia lisäämällä siihen haluttuja lisäominaisuuksia. 
- Commit viestit ovat kuvaavia ja selkeitä.
- En keksi mitään kehitettävää, hyvältä näyttää!

**Comment by ruokokoski** [comment]
Olisihan se kiva jos joku sovellusta oikeasti saisi testattua ja annettua palautetta.

**Comment by sandraole** [comment]
Hei,

Sain tänään oman lokaalin ongelman korjattua ohjaajan avustuksella, joka ei näköjään liittynyt siihen miksen saa sinun sovellusta auki. Olen yrittänyt vielä vertaisarvioinnin palautuksen jälkeenkin saada sovellustasi toimimaan, mutta se ei siitä huolimatta onnistu. Osaisitko sinä auttaa minua, sillä mielelläni testaisin sovellusta. En olisi muuten käyttänyt näin paljon aikaa siihen, että saisin sen toimimaan. 

Teen kuten sinun README ohjeissa on mainittu ja mitä tsohan materiaaleissa lukee. Varmistan myös aina, että vanha tietokanta on tyhjennetty postgreissä. Siitä huolimatta, kun yritän kirjautua niin saan virheilmoituksen "Internal Server Error - The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.". Osaisitko sanoa mistä se johtuu ja mitä voin tehdä asialle? Jos saat jotenkin neuvottua, niin ilomielin kokeilen ja arvioin sovelluksesi uudelleen tähän.
