### ISSUE TITLE
Vertaisarviointi 2 (11.10.)

### ISSUE THREAD

**Issue by jmakine** [Ethervortex/opeapu#2]
**Koodista:**

README kuvaa hyvin sovelluksen toimintoja ja käyttötarkoitusta, ja ohjeet sovelluksen käyttöönottoon toimii. Koodi on hyvin jäsenneltyä ja sopiviin toiminnallisuuksiin pilkottu, joten sitä on helppo tutkia ja tulkita. Tietokanta on siisti ja simppeli, ja mahdollisuus ladata testidata kantaan on mainio lisä.

**Sovelluksesta:**

Yleisilme on siisti, kirjautuminen sisään ja ulos toimii, kuten muutkin sovelluksen toiminnot. Navigointi sivujen välillä hyvin toteutettu, navigaatiopalkit asianmukaisesti nimetty, ja sivut näyttävät sen, mitä nimen perusteella olettaa voi. Etusivun kuvaus sovelluksesta oikein hyvä ja kattava.

**Muutama korjattava huomio:**

- Jos jättää kurssin arvosana -kentän tyhjäksi ja painaa ’Tallenna’, tulee ’Internal Server Error’.
- Lomakkeista puuttuu cfrs_token ja vastaavasti lomakkeen käsittelijöistä puuttuu sen tarkistus. Kirjautumisen yhteydessä on kuitenkin luotu ’session[”csrf_token”]’, sitä vaan ei ole käytetty.

**Muutama pienempi huomio:**

- Notifikaatiot puuttuu ainakin oppilaan onnistuneesta poistosta, oppilaiden onnistuneesta lisäämisestä kurssille, kurssin onnistuneesta poistosta.
- Kurssin poistamisen nappula on vähän piilossa, kun sen löytää vain ’Lisää oppilaita’ -nappulan takaa ’Kurssit’ sivulla. Tälle voisi miettiä jotain vaihtoehtoista ratkaisua, helpoimmalla varmaan pääsisi esim. nimeämällä ’Lisää oppilaita’ -> ’Näytä tiedot’ tai jotain vastaavaa.
- ’Tuntiaktiivisuus’ voisi näyttää oletuksena valitun kurssin kyseiselle päivälle annetut aktiivisuuspisteet, jos opettaja on niitä jo tallentanut. Nyt ’Tuntiaktiivisuus’ näyttää aina tyhjää oletuksena, vaikka päivän merkinnät olisi jo tehty. Ja jos osa merkinnöistä on tehty, mutta haluaisi merkitä loppujenkin opiskelijoiden pisteet, ei niitä näy taulukosta, vaan kaikki pitää lisätä uudelleen.
- Tekstien ’None’ sijaan taulukoissa ja teksteissä voisi näkyä esim. ’-’. Tämä nyt ihan minimaalinen visuaalinen huomio vain.

**Comment by ruokokoski** [comment]
Kiitos erinomaisesta palautteesta. Arvosana-kentän bugia en ollut edes huomannut ja csrf_tokenin käyttökin oli tyystin unohtunut. Pienemmätkin huomiot ovat hyviä ja yritän viilata toiminnallisuutta näiden perusteella vielä paremmaksi.
